In [1]:

import pandas as pd
from pathlib import Path

processed_path = Path("../data/processed")

sleep_df = pd.read_csv(processed_path / "minuteSleep_clean.csv")
weight_df = pd.read_csv(processed_path / "weightLogInfo_clean.csv")

sleep_df["date"] = pd.to_datetime(sleep_df["date"])
weight_df["Date"] = pd.to_datetime(weight_df["Date"])

In [2]:
sleep_df.head()

           Id                date  value        logId
0  1503960366 2016-03-13 02:39:30      1  11114919637
1  1503960366 2016-03-13 02:40:30      1  11114919637
2  1503960366 2016-03-13 02:41:30      1  11114919637
3  1503960366 2016-03-13 02:42:30      1  11114919637
4  1503960366 2016-03-13 02:43:30      1  11114919637

In [3]:
sleep_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198034 entries, 0 to 198033
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Id      198034 non-null  int64
 1   date    198034 non-null  datetime64[ns]
 2   value   198034 non-null  int64
 3   logId   198034 non-null  int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 6.0 MB

In [4]:
sleep_df.describe()

,Id,date,value,logId
count,1.980340e+05,198034,198034.000000,1.980340e+05
mean,4.825642e+09,2016-03-27 12:03:01.066862336,1.085889,1.124134e+10
min,1.503960e+09,2016-03-11 21:19:30,1.000000,1.110365e+10
25%,2.347168e+09,2016-03-19 06:35:00,1.000000,1.116551e+10
50%,4.702922e+09,2016-03-28 02:58:00,1.000000,1.124395e+10
75%,6.775889e+09,2016-04-04 02:43:00,1.000000,1.130901e+10
max,8.792010e+09,2016-04-12 08:35:00,3.000000,1.137488e+10
std,2.176659e+09,NaN,0.314393,7.962745e+07

In [5]:
sleep_df["value"].value_counts().sort_index()

value
1    183038
2     12983
3      2013
Name: count, dtype: int64

In [6]:
sleep_df["sleep_minutes"] = 1

In [7]:
daily_sleep = (
    sleep_df
    .groupby(["Id", sleep_df["date"].dt.date])["sleep_minutes"]
    .sum()
    .reset_index()
)

In [8]:
daily_sleep.head(10)

           Id        date  sleep_minutes
0  1503960366  2016-03-13            426
1  1503960366  2016-03-14            386
2  1503960366  2016-03-15            335
3  1503960366  2016-03-16            366
4  1503960366  2016-03-17            437
5  1503960366  2016-03-18            411
6  1503960366  2016-03-19            468
7  1503960366  2016-03-20            476
8  1503960366  2016-03-21            427
9  1503960366  2016-03-23            297

In [9]:
daily_sleep.shape

(467, 3)

In [10]:
sleep_df["value"].value_counts().sort_index()

value
1    183038
2     12983
3      2013
Name: count, dtype: int64

In [11]:
sleep_df[sleep_df["Id"] == 1503960366].head(20)

            Id                date  value        logId  sleep_minutes
0   1503960366 2016-03-13 02:39:30      1  11114919637              1
1   1503960366 2016-03-13 02:40:30      1  11114919637              1
2   1503960366 2016-03-13 02:41:30      1  11114919637              1
3   1503960366 2016-03-13 02:42:30      1  11114919637              1
4   1503960366 2016-03-13 02:43:30      1  11114919637              1
5   1503960366 2016-03-13 02:44:30      1  11114919637              1
6   1503960366 2016-03-13 02:45:30      2  11114919637              1
7   1503960366 2016-03-13 02:46:30      2  11114919637              1
8   1503960366 2016-03-13 02:47:30      1  11114919637              1
9   1503960366 2016-03-13 02:48:30      1  11114919637              1
10  1503960366 2016-03-13 02:49:30      2  11114919637              1
11  1503960366 2016-03-13 02:50:30      2  11114919637              1
12  1503960366 2016-03-13 02:51:30      1  11114919637              1
13  1503960366 2016-03-13 02:52:30      1  11114919637              1
14  1503960366 2016-03-13 02:53:30      1  11114919637              1
15  1503960366 2016-03-13 02:54:30      1  11114919637              1
16  1503960366 2016-03-13 02:55:30      1  11114919637              1
17  1503960366 2016-03-13 02:56:30      1  11114919637              1
18  1503960366 2016-03-13 02:57:30      1  11114919637              1
19  1503960366 2016-03-13 02:58:30      1  11114919637              1

In [12]:
sleep_df["value"].value_counts().sort_index()

value
1    183038
2     12983
3      2013
Name: count, dtype: int64

In [13]:
import pandas as pd

activity_df = pd.read_csv("../data/raw/dailyActivity_merged.csv")

In [14]:
activity_df.shape

(457, 15)

In [15]:
activity_df["ActivityDate"] = pd.to_datetime(activity_df["ActivityDate"])

In [16]:
activity_df = activity_df.rename(
    columns={"ActivityDate": "date"}
)

In [17]:
activity_df.columns

Index(['Id', 'date', 'TotalSteps', 'TotalDistance', 'TrackerDistance',
       'LoggedActivitiesDistance', 'VeryActiveDistance',
       'ModeratelyActiveDistance', 'LightActiveDistance',
       'SedentaryActiveDistance', 'VeryActiveMinutes', 'FairlyActiveMinutes',
       'LightlyActiveMinutes', 'SedentaryMinutes', 'Calories'],
      dtype='object')

In [18]:
daily_sleep = (
    sleep_df
    .groupby(["Id", sleep_df["date"].dt.date])["value"]
    .sum()
    .reset_index()
)

In [19]:
daily_sleep.head()

           Id        date  value
0  1503960366  2016-03-13    441
1  1503960366  2016-03-14    423
2  1503960366  2016-03-15    365
3  1503960366  2016-03-16    404
4  1503960366  2016-03-17    473

In [20]:
daily_sleep = daily_sleep.rename(
    columns={"value": "recorded_sleep_minutes"}
)

In [22]:
daily_sleep["date"] = pd.to_datetime(daily_sleep["date"])

In [23]:
daily_data = activity_df.merge(
    daily_sleep,
    on=["Id", "date"],
    how="inner"
)

In [24]:
daily_data.shape

(199, 16)

In [25]:
daily_data.isna().sum()

Id                          0
date                        0
TotalSteps                  0
TotalDistance               0
TrackerDistance             0
LoggedActivitiesDistance    0
VeryActiveDistance          0
ModeratelyActiveDistance    0
LightActiveDistance         0
SedentaryActiveDistance     0
VeryActiveMinutes           0
FairlyActiveMinutes         0
LightlyActiveMinutes        0
SedentaryMinutes            0
Calories                    0
recorded_sleep_minutes      0
dtype: int64

In [26]:
baseline = (
    daily_data
    .groupby("Id")["TotalSteps"]
    .mean()
    .reset_index()
)

In [27]:
baseline.head(2)

           Id    TotalSteps
0  1503960366  12520.214286
1  1844505072   3594.000000

In [28]:
baseline = baseline.rename(
    columns={"TotalSteps": "baseline_steps"}
)

In [29]:
baseline.columns

Index(['Id', 'baseline_steps'], dtype='object')

In [30]:
daily_data = daily_data.merge(
    baseline,
    on="Id",
    how="left"
)

In [31]:
daily_data.head()

,Id,date,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,recorded_sleep_minutes,baseline_steps
0,1503960366,2016-03-25,11004,7.11,7.11,0.0,2.57,0.46,4.07,0.0,33,12,205,804,1819,424,12520.214286
1,1503960366,2016-03-26,17609,11.55,11.55,0.0,6.92,0.73,3.91,0.0,89,17,274,588,2154,511,12520.214286
2,1503960366,2016-03-27,12736,8.53,8.53,0.0,4.66,0.16,3.71,0.0,56,5,268,605,1944,533,12520.214286
3,1503960366,2016-03-28,13231,8.93,8.93,0.0,3.19,0.79,4.95,0.0,39,20,224,1080,1932,81,12520.214286
4,1503960366,2016-03-29,12041,7.85,7.85,0.0,2.16,1.09,4.61,0.0,28,28,243,763,1886,411,12520.214286

In [32]:
daily_data["steps_deviation"] = (
    daily_data["TotalSteps"] - daily_data["baseline_steps"]
)

In [33]:
daily_data[["Id", "date", "TotalSteps", "baseline_steps", "steps_deviation"]].head()

           Id       date  TotalSteps  baseline_steps  steps_deviation
0  1503960366 2016-03-25       11004    12520.214286     -1516.214286
1  1503960366 2016-03-26       17609    12520.214286      5088.785714
2  1503960366 2016-03-27       12736    12520.214286       215.785714
3  1503960366 2016-03-28       13231    12520.214286       710.785714
4  1503960366 2016-03-29       12041    12520.214286      -479.214286

In [34]:
daily_data["steps_deviation_pct"] = (
    daily_data["steps_deviation"]
    / daily_data["baseline_steps"]
) * 100

In [35]:
daily_data[
    ["Id", "date", "TotalSteps", "baseline_steps", "steps_deviation_pct"]
].head()

           Id       date  TotalSteps  baseline_steps  steps_deviation_pct
0  1503960366 2016-03-25       11004    12520.214286           -12.110130
1  1503960366 2016-03-26       17609    12520.214286            40.644558
2  1503960366 2016-03-27       12736    12520.214286             1.723499
3  1503960366 2016-03-28       13231    12520.214286             5.677105
4  1503960366 2016-03-29       12041    12520.214286            -3.827525

In [36]:
sleep_baseline = (
    daily_data
    .groupby("Id")["recorded_sleep_minutes"]
    .mean()
    .reset_index()
)

In [37]:
sleep_baseline = sleep_baseline.rename(
    columns={"recorded_sleep_minutes": "baseline_sleep_minutes"}
)

In [38]:
daily_data = daily_data.merge(
    sleep_baseline,
    on="Id",
    how="left"
)

In [39]:
daily_data[["Id", "date", "recorded_sleep_minutes", "baseline_sleep_minutes"]].head()

           Id       date  recorded_sleep_minutes  baseline_sleep_minutes
0  1503960366 2016-03-25                     424              411.071429
1  1503960366 2016-03-26                     511              411.071429
2  1503960366 2016-03-27                     533              411.071429
3  1503960366 2016-03-28                      81              411.071429
4  1503960366 2016-03-29                     411              411.071429

In [40]:
daily_data["sleep_deviation"] = (
    daily_data["recorded_sleep_minutes"]
    - daily_data["baseline_sleep_minutes"]
)

In [41]:
daily_data["sleep_deviation_pct"] = (
    daily_data["sleep_deviation"]
    / daily_data["baseline_sleep_minutes"]
) * 100

In [42]:
daily_data[
    ["Id", "date",
     "recorded_sleep_minutes",
     "baseline_sleep_minutes",
     "sleep_deviation_pct"]
].head()

,Id,date,recorded_sleep_minutes,baseline_sleep_minutes,sleep_deviation_pct
0,1503960366,2016-03-25,424,411.071429,3.145091
1,1503960366,2016-03-26,511,411.071429,24.309296
2,1503960366,2016-03-27,533,411.071429,29.661164
3,1503960366,2016-03-28,81,411.071429,-80.295395
4,1503960366,2016-03-29,411,411.071429,-0.017376

In [43]:
daily_data.columns.tolist()

['Id',
 'date',
 'TotalSteps',
 'TotalDistance',
 'TrackerDistance',
 'LoggedActivitiesDistance',
 'VeryActiveDistance',
 'ModeratelyActiveDistance',
 'LightActiveDistance',
 'SedentaryActiveDistance',
 'VeryActiveMinutes',
 'FairlyActiveMinutes',
 'LightlyActiveMinutes',
 'SedentaryMinutes',
 'Calories',
 'recorded_sleep_minutes',
 'baseline_steps',
 'steps_deviation',
 'steps_deviation_pct',
 'baseline_sleep_minutes',
 'sleep_deviation',
 'sleep_deviation_pct']

In [45]:
daily_data = daily_data.sort_values(
    ["Id", "date"]
).reset_index(drop=True)

In [46]:
daily_data[["Id", "date"]].head(10)

           Id       date
0  1503960366 2016-03-25
1  1503960366 2016-03-26
2  1503960366 2016-03-27
3  1503960366 2016-03-28
4  1503960366 2016-03-29
5  1503960366 2016-03-31
6  1503960366 2016-04-01
7  1503960366 2016-04-02
8  1503960366 2016-04-03
9  1503960366 2016-04-04

In [47]:
daily_data["day_number"] = (
    daily_data.groupby("Id").cumcount() + 1
)

In [48]:
daily_data[["Id", "date", "day_number"]].head(10)

           Id       date  day_number
0  1503960366 2016-03-25           1
1  1503960366 2016-03-26           2
2  1503960366 2016-03-27           3
3  1503960366 2016-03-28           4
4  1503960366 2016-03-29           5
5  1503960366 2016-03-31           6
6  1503960366 2016-04-01           7
7  1503960366 2016-04-02           8
8  1503960366 2016-04-03           9
9  1503960366 2016-04-04          10

In [49]:
daily_data["is_baseline"] = daily_data["day_number"] <= 7

In [50]:
daily_data[["Id", "date", "day_number", "is_baseline"]].head(10)

           Id       date  day_number  is_baseline
0  1503960366 2016-03-25           1         True
1  1503960366 2016-03-26           2         True
2  1503960366 2016-03-27           3         True
3  1503960366 2016-03-28           4         True
4  1503960366 2016-03-29           5         True
5  1503960366 2016-03-31           6         True
6  1503960366 2016-04-01           7         True
7  1503960366 2016-04-02           8        False
8  1503960366 2016-04-03           9        False
9  1503960366 2016-04-04          10        False

In [51]:
baseline_7d = (
    daily_data[daily_data["is_baseline"]]
    .groupby("Id")["TotalSteps"]
    .mean()
    .reset_index()
)

In [52]:
daily_data[daily_data["is_baseline"]]

,Id,date,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,...,Calories,recorded_sleep_minutes,baseline_steps,steps_deviation,steps_deviation_pct,baseline_sleep_minutes,sleep_deviation,sleep_deviation_pct,day_number,is_baseline
0,1503960366,2016-03-25,11004,7.11,7.11,0.0,2.57,0.46,4.07,0.0,...,1819,424,12520.214286,-1516.214286,-12.110130,411.071429,12.928571,3.145091,1,True
1,1503960366,2016-03-26,17609,11.55,11.55,0.0,6.92,0.73,3.91,0.0,...,2154,511,12520.214286,5088.785714,40.644558,411.071429,99.928571,24.309296,2,True
2,1503960366,2016-03-27,12736,8.53,8.53,0.0,4.66,0.16,3.71,0.0,...,1944,533,12520.214286,215.785714,1.723499,411.071429,121.928571,29.661164,3,True
3,1503960366,2016-03-28,13231,8.93,8.93,0.0,3.19,0.79,4.95,0.0,...,1932,81,12520.214286,710.785714,5.677105,411.071429,-330.071429,-80.295395,4,True
4,1503960366,2016-03-29,12041,7.85,7.85,0.0,2.16,1.09,4.61,0.0,...,1886,411,12520.214286,-479.214286,-3.827525,411.071429,-0.071429,-0.017376,5,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,8792009665,2016-04-04,3821,2.45,2.45,0.0,0.00,0.22,2.23,0.0,...,2229,630,2985.500000,835.500000,27.985262,544.500000,85.500000,15.702479,3,True
194,8792009665,2016-04-05,2332,1.49,1.49,0.0,0.01,0.18,1.30,0.0,...,2100,455,2985.500000,-653.500000,-21.889131,544.500000,-89.500000,-16.437098,4,True
195,8792009665,2016-04-06,2121,1.36,1.36,0.0,0.00,0.00,1.36,0.0,...,2114,507,2985.500000,-864.500000,-28.956624,544.500000,-37.500000,-6.887052,5,True
196,8792009665,2016-04-07,1291,0.83,0.83,0.0,0.00,0.00,0.83,0.0,...,1961,510,2985.500000,-1694.500000,-56.757662,544.500000,-34.500000,-6.336088,6,True
197,8792009665,2016-04-08,1467,0.94,0.94,0.0,0.10,0.21,0.63,0.0,...,1953,478,2985.500000,-1518.500000,-50.862502,544.500000,-66.500000,-12.213039,7,True

In [53]:
baseline_7d.head()

           Id    TotalSteps
0  1503960366  13019.857143
1  1844505072   3594.000000
2  1927972279   3077.857143
3  2026352035   3487.571429
4  2347167796   9870.142857

In [54]:
baseline_7d = baseline_7d.rename(
    columns={"TotalSteps": "baseline_steps_7d"}
)

In [55]:
daily_data = daily_data.merge(
    baseline_7d,
    on="Id",
    how="left"
)

In [56]:
daily_data["steps_deviation_7d"] = (
    daily_data["TotalSteps"] - daily_data["baseline_steps_7d"]
)

In [57]:
daily_data["steps_deviation_7d_pct"] = (
    daily_data["steps_deviation_7d"]
    / daily_data["baseline_steps_7d"]
) * 100

In [58]:
sleep_baseline_7d = (
    daily_data[daily_data["is_baseline"]]
    .groupby("Id")["recorded_sleep_minutes"]
    .mean()
    .reset_index()
)

In [59]:
sleep_baseline_7d = sleep_baseline_7d.rename(
    columns={"recorded_sleep_minutes": "baseline_sleep_7d"}
)

In [60]:
sleep_baseline_7d.head()

           Id  baseline_sleep_7d
0  1503960366         379.714286
1  1844505072         636.500000
2  1927972279         331.857143
3  2026352035         617.428571
4  2347167796         561.714286

In [61]:
daily_data = daily_data.merge(
    sleep_baseline_7d,
    on="Id",
    how="left"
)

In [62]:
# ==========================================
# DAY 6 — FINAL FEATURE ENGINEERING
# ==========================================

# 1. Sleep deviation from 7-day personal baseline
daily_data["sleep_deviation_7d"] = (
    daily_data["recorded_sleep_minutes"]
    - daily_data["baseline_sleep_7d"]
)

# 2. Sleep percentage deviation
daily_data["sleep_deviation_7d_pct"] = (
    daily_data["sleep_deviation_7d"]
    / daily_data["baseline_sleep_7d"]
) * 100


# 3. Sort chronologically before rolling features
daily_data = daily_data.sort_values(
    ["Id", "date"]
).reset_index(drop=True)


# 4. 3-observation rolling average of steps
daily_data["steps_rolling_3d"] = (
    daily_data
    .groupby("Id")["TotalSteps"]
    .transform(
        lambda x: x.rolling(window=3, min_periods=1).mean()
    )
)


# 5. 3-observation rolling average of recorded sleep
daily_data["sleep_rolling_3d"] = (
    daily_data
    .groupby("Id")["recorded_sleep_minutes"]
    .transform(
        lambda x: x.rolling(window=3, min_periods=1).mean()
    )
)


# 6. Activity ratio relative to personal baseline
daily_data["activity_ratio"] = (
    daily_data["TotalSteps"]
    / daily_data["baseline_steps_7d"]
)


# 7. Sleep ratio relative to personal baseline
daily_data["sleep_ratio"] = (
    daily_data["recorded_sleep_minutes"]
    / daily_data["baseline_sleep_7d"]
)


# 8. Select final ML-ready features
feature_columns = [
    "Id",
    "date",
    "TotalSteps",
    "Calories",
    "VeryActiveMinutes",
    "FairlyActiveMinutes",
    "LightlyActiveMinutes",
    "SedentaryMinutes",
    "recorded_sleep_minutes",
    "baseline_steps_7d",
    "baseline_sleep_7d",
    "steps_deviation_7d",
    "steps_deviation_7d_pct",
    "sleep_deviation_7d",
    "sleep_deviation_7d_pct",
    "steps_rolling_3d",
    "sleep_rolling_3d",
    "activity_ratio",
    "sleep_ratio",
    "day_number",
    "is_baseline"
]

feature_data = daily_data[feature_columns].copy()


# 9. Basic validation
print("Shape:", feature_data.shape)
print("\nMissing values:")
print(feature_data.isna().sum())

print("\nDuplicate rows:")
print(feature_data.duplicated().sum())

print("\nFeature dataset preview:")
display(feature_data.head())


# 10. Save processed feature dataset
from pathlib import Path

processed_path = Path("../data/processed")
processed_path.mkdir(parents=True, exist_ok=True)

feature_data.to_csv(
    processed_path / "daily_features.csv",
    index=False
)

print("\nFeature engineering completed successfully.")
print("Saved to: ../data/processed/daily_features.csv")

Shape: (199, 21)

Missing values:
Id                        0
date                      0
TotalSteps                0
Calories                  0
VeryActiveMinutes         0
FairlyActiveMinutes       0
LightlyActiveMinutes      0
SedentaryMinutes          0
recorded_sleep_minutes    0
baseline_steps_7d         0
baseline_sleep_7d         0
steps_deviation_7d        0
steps_deviation_7d_pct    0
sleep_deviation_7d        0
sleep_deviation_7d_pct    0
steps_rolling_3d          0
sleep_rolling_3d          0
activity_ratio            0
sleep_ratio               0
day_number                0
is_baseline               0
dtype: int64

Duplicate rows:
0

Feature dataset preview:

,Id,date,TotalSteps,Calories,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,recorded_sleep_minutes,baseline_steps_7d,...,steps_deviation_7d,steps_deviation_7d_pct,sleep_deviation_7d,sleep_deviation_7d_pct,steps_rolling_3d,sleep_rolling_3d,activity_ratio,sleep_ratio,day_number,is_baseline
0,1503960366,2016-03-25,11004,1819,33,12,205,804,424,13019.857143,...,-2015.857143,-15.482944,44.285714,11.662904,11004.000000,424.000000,0.845171,1.116629,1,True
1,1503960366,2016-03-26,17609,2154,89,17,274,588,511,13019.857143,...,4589.142857,35.247260,131.285714,34.574868,14306.500000,467.500000,1.352473,1.345749,2,True
2,1503960366,2016-03-27,12736,1944,56,5,268,605,533,13019.857143,...,-283.857143,-2.180186,153.285714,40.368698,13783.000000,489.333333,0.978198,1.403687,3,True
3,1503960366,2016-03-28,13231,1932,39,20,224,1080,81,13019.857143,...,211.142857,1.621699,-298.714286,-78.668172,14525.333333,375.000000,1.016217,0.213318,4,True
4,1503960366,2016-03-29,12041,1886,28,28,243,763,411,13019.857143,...,-978.857143,-7.518187,31.285714,8.239278,12669.333333,341.666667,0.924818,1.082393,5,True

Feature engineering completed successfully.
Saved to: ../data/processed/daily_features.csv